<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20325" started-at="2018-08-31T06:10:06Z" finished-at="2018-08-31T06:10:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20325" started-at="2018-08-31T06:10:06Z" finished-at="2018-08-31T06:10:26Z">
      <class name="com.ddf.RediffMailLogin">
        <test-method status="FAIL" signature="loginToRediff(java.lang.String, java.lang.String)[pri:1, instance:com.ddf.RediffMailLogin@54bff557]" name="loginToRediff" duration-ms="7088" started-at="2018-08-31T11:40:06Z" data-provider="credentials" finished-at="2018-08-31T11:40:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rediffmail NG - Login error] but found [Rediffmail]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rediffmail NG - Login error] but found [Rediffmail]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.ddf.RediffMailLogin.loginToRediff(RediffMailLogin.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToRediff -->
        <test-method status="PASS" signature="loginToRediff(java.lang.String, java.lang.String)[pri:1, instance:com.ddf.RediffMailLogin@54bff557]" name="loginToRediff" duration-ms="4589" started-at="2018-08-31T11:40:13Z" data-provider="credentials" finished-at="2018-08-31T11:40:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo12]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToRediff -->
        <test-method status="PASS" signature="loginToRediff(java.lang.String, java.lang.String)[pri:1, instance:com.ddf.RediffMailLogin@54bff557]" name="loginToRediff" duration-ms="8526" started-at="2018-08-31T11:40:18Z" data-provider="credentials" finished-at="2018-08-31T11:40:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[madhusudan405@rediffmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dontgiveup]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToRediff -->
        <test-method status="SKIP" signature="logout()[pri:2, instance:com.ddf.RediffMailLogin@54bff557]" name="logout" duration-ms="0" started-at="2018-08-31T11:40:26Z" depends-on-methods="com.ddf.RediffMailLogin.loginToRediff" finished-at="2018-08-31T11:40:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RediffMailLogin.logout()[pri:2, instance:com.ddf.RediffMailLogin@54bff557] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RediffMailLogin.logout()[pri:2, instance:com.ddf.RediffMailLogin@54bff557] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.ddf.RediffMailLogin@54bff557]" name="teardown" is-config="true" duration-ms="74" started-at="2018-08-31T11:40:26Z" finished-at="2018-08-31T11:40:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.ddf.RediffMailLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
